USE [master]
GO
/****** Object:  Database [SignalR]    Script Date: 24/08/2022 12:51:10 PM ******/
CREATE DATABASE [SignalR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SignalR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SignalR.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SignalR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SignalR_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SignalR] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SignalR].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SignalR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SignalR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SignalR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SignalR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SignalR] SET ARITHABORT OFF 
GO
ALTER DATABASE [SignalR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SignalR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SignalR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SignalR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SignalR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SignalR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SignalR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SignalR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SignalR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SignalR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SignalR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SignalR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SignalR] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SignalR] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SignalR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SignalR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SignalR] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SignalR] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SignalR] SET  MULTI_USER 
GO
ALTER DATABASE [SignalR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SignalR] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SignalR] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SignalR] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SignalR] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SignalR] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SignalR] SET QUERY_STORE = OFF
GO
USE [SignalR]
GO
/****** Object:  User [Adham]    Script Date: 24/08/2022 12:51:11 PM ******/
CREATE USER [Adham] FOR LOGIN [Adham] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[connections]    Script Date: 24/08/2022 12:51:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[connections](
	[id] [uniqueidentifier] NOT NULL,
	[personId] [uniqueidentifier] NOT NULL,
	[signalrId] [nvarchar](22) NOT NULL,
	[timeStamp] [datetime] NOT NULL,
 CONSTRAINT [PK_connections] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[person]    Script Date: 24/08/2022 12:51:11 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[person](
	[id] [uniqueidentifier] NOT NULL,
	[name] [nvarchar](100) NOT NULL,
	[username] [nvarchar](50) NOT NULL,
	[password] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_person] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[connections] ADD  CONSTRAINT [DF_connections_id]  DEFAULT (newid()) FOR [id]
GO
ALTER TABLE [dbo].[person] ADD  CONSTRAINT [DF_person_id]  DEFAULT (newid()) FOR [id]
GO
USE [master]
GO
ALTER DATABASE [SignalR] SET  READ_WRITE 
GO
